# Generated by Django 3.1.1 on 2021-06-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210607_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
