# Generated by Django 3.1.1 on 2021-06-01 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210520_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 18, 34, 8, 487344, tzinfo=utc)),
        ),
    ]
