# Generated by Django 3.1.1 on 2021-06-08 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='saved',
            field=models.ManyToManyField(related_name='user_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
