# Generated by Django 3.1.1 on 2021-06-02 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210602_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 2, 9, 31, 35, 181954, tzinfo=utc)),
        ),
    ]
