# Generated by Django 3.1.1 on 2021-06-03 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210602_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 10, 34, 37, 677858, tzinfo=utc)),
        ),
    ]
