# Generated by Django 3.1.1 on 2021-06-03 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210603_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 3, 10, 59, 44, 258882, tzinfo=utc)),
        ),
    ]
