# Generated by Django 3.1.1 on 2021-06-04 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210604_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 14, 35, 31, 189349, tzinfo=utc)),
        ),
    ]
