# Generated by Django 3.1.1 on 2021-06-04 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210604_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 4, 18, 20, 55, 222861, tzinfo=utc)),
        ),
    ]
